services:

  application:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PIDFILE=tmp/pids/server_1.pid
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/www/malinki_tracker
    depends_on:
      - db
      
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: malinki_tracker
      POSTGRES_PASSWORD: kj98bO_oui78GH
      PGDATA: /tmp
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      # - ./config/docker/gis.sh:/docker-entrypoint-initdb.d/gis.sh
      # If postgres container contain file with permissions postgres:postrges
      # stop container then comment string below, up container without string and rebuild with uncommented string
      # problem seen on docker-desktop mac os x
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf

volumes:
  postgres:
    driver: local
